### PR TITLE
French translation of gitready

### PR DESCRIPTION
**Pull request by edouardswiac**
Hi,

I'd like to contribute to gitready with a french translation. 
The layout and a first post are translated. I will gradually translate each posts.

Regards,
Edouard

### CODE REVIEW

**Comment by qrush** [comment]
Cool, I'll try to find some time this week to hook up the `fr` subdomain.

**Comment by qrush** [comment]
Sorry this took so long. DNS should be resolving soon for the `fr` subdomain. If you're going to do more translations, tell me and I'll add you to the gitready org so you can write and deploy more!

**Comment by qrush** [comment]
Done:

http://fr.gitready.com/

Are more articles supposed to be published?

**Comment by edouardswiac** [comment]
Not at the moment, but very soon!

**Pull request closed without merging**
