### PR TITLE
translate gitready into indonesian

### PR DESCRIPTION
**Pull request by pyk**
i'm currently working on translate all blog post in gitready.com into indonesian. so far, this is what i've done

### CODE REVIEW

**Comment by ngulden** [comment]
Hi @peeyek,

thank you for your contribution. I've created a new branch 'id' at gitready/gitready and merged your changes in there. I therefore close this pull request.

Best regards

**Comment by pyk** [comment]
thanks @ngulden :)

**Comment by pyk** [comment]
hai @ngulden 

will be this indonesian version have sub domain like the other language? i mean like this id.gitready.com ?

**Comment by ngulden** [comment]
Hi @peyeek,

there has been some movement around gitready the last couple months and some other languages have been added. Usally @qrush did all the infrastructure stuff and created all the pages through Github. Besides Indonesian also Chinese and Greek have been added. 

Yesterday, I saw that the subdomains are not created automatically. I try to have a look at it over the next couple days. Otherwise, qrush the founder of the project has to take care of it. It is not documented how to deal with for gitready.

Best regards

**Comment by ngulden** [comment]
Hi @peeyek,

I cannot create the appropriate repository below gitready for Indonesian, because of insufficient rights. I've opened issue #38 and assigned it to @qrush.

Best regards

**Comment by siriokun** [comment]
When exactly will @qrush make this to live at http://id.gitready.com/beginner/2009/01/11-reverting-files.html ?

Cheers

**Pull request closed without merging**
