### PR TITLE
He

### PR DESCRIPTION
**Pull request by shaiguitar**
Hebrew. Just layouts for now. Was there any other file needed to be changed, or was that the basics?

### CODE REVIEW

**Comment by qrush** [comment]
Hey there...finally getting around to checking out gitready again...

This pull looks good, but it would end up with posts translated. If you get a post or two translated I'll get it published and out on he.gitready.com.

**Comment by shaiguitar** [comment]
I forgot what was done here it's been a while. Can you be more specific on what the problem is and what you need done?

**Comment by qrush** [comment]
No worries!

So you just "hid" every post...so the front page will be translated, but none of the individual blog posts are. From here, translators usually will pick off a post they want to translate into their language, and once done, remove the `published: false` line.

**Comment by shaiguitar** [comment]
Oh, gotcha. Been a while. 

I don't have time at this specific moment, but I think if you published the he site with posts or even a post in english (so just rm the pushlished: false stuff somewhere) it would still be beneficial; It'll be out there and then more people will consider translating.

**Comment by qrush** [comment]
Sure, I can still do that.

**Comment by qrush** [comment]
Done! http://he.gitready.com/ Added a helpful post too to encourage some translators.

**Comment by shaiguitar** [comment]
Sweet, thanks!

**Pull request closed without merging**
