### PR TITLE
Japanese translation of gitready

### PR DESCRIPTION
**Pull request by oshow**
Hi,

I translated some gitready posts into Japanese!
I will also translate all other posts.

### CODE REVIEW

**Comment by ngulden** [comment]
Hi, 

thank's a lot for the japanese translation. I'll hopefully take a look at it at the weekend.

**Comment by oshow** [comment]
Thank you for your response!
Please point out any mistakes if my commits don't work to publish gitready web site.

**Comment by ngulden** [comment]
I created a new branch ja on gitready/gitready and pushed your translation there. But qrush needs to do all the stuff that there'll be a http://ja.gitready.com/ page.

**Comment by ngulden** [comment]
@qrush would you please create all the other stuff?

**Comment by qrush** [comment]
Done, and deployed to all subdomains. Sorry about the delay here. :[

http://ja.gitready.com/

**Pull request closed without merging**
