### PR TITLE
Add guest post: ribbon/catchup trick

### PR DESCRIPTION
**Pull request by joliss**
Let me know if everything is OK with it! :-)

### CODE REVIEW

**Comment by joliss** [comment]
_nags @qrush gently_ ;-)

**Comment by qrush** [comment]
I'll take a look today...been really busy, moving this weekend. Sorry :(

**Comment by joliss** [comment]
Hey Nick, just wanted to check if you were going to merge this -- if not, I'd go ahead post it on my own blog.

(I'm also on XMPP at joliss42@gmail.com if there's any issues to be ironed out.)

**Comment by qrush** [comment]
I'm really sorry, but I dropped the ball here. Just merged/deployed/etc. I'll add you as a contributor if you want to write more :)

**Comment by joliss** [comment]
Haha, don't worry -- thanks for merging! And thanks for adding me as a contributor. :)

Happy holidays :)

**Pull request merged**
