### PR TITLE
promote gitolite

### PR DESCRIPTION
**Pull request by hemmecke**

### CODE REVIEW

**Comment by ngulden** [comment]
Hello hemmecke,

I suggest you add the date for your update to the text of your pull request. That makes it clear to reader within the text when the update has been added. After that I would be happy to accept your pull request.

Best regards,
ngulden

**Comment by hemmecke** [comment]
I would like that my two commits were **squashed** together. I could have amended my first commit, but I didn't know how github will handle this and whether I should better then open up a new pull request. So if you also just like **one** commit, tell me how I should prepare it "in the github way".

**Comment by joliss** [comment]
I'm not the repo maintainer, but you can in fact just squash them (`git rebase --interactive origin`, or `HEAD~2`), do a `git push -f`, and GitHub will automatically update this pull request.

**Comment by ngulden** [comment]
Well, I think it's ok to have those two commits. That's what code reviews are for, aren't they ;-)?

@hemmecke: If you are fine with it, I would just accept your merge. I'm looking forward to your response.

**Comment by hemmecke** [comment]
Hi ngulden, you've just hit me in the right moment. I've squashed the two commits.

**Pull request merged**
